[workspace]
members = [
    "crates/libzmq-core",
    "crates/libzmq",
    "crates/libzmq-ffi",
    "crates/libzmq-sys",
    "crates/libzmq-test-harness",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/zeromq/libzmq"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
missing_safety_doc = "deny"

[workspace.dependencies]
libzmq-core = { path = "crates/libzmq-core" }
libzmq-sys = { path = "crates/libzmq-sys" }
