[package]
name = "libzmq-sys"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "libzmq_sys"

[features]
default = []
full = ["gssapi", "norm", "openpgm"]
gssapi = []
norm = []
openpgm = []

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Networking_WinSock"] }

[lints]
workspace = true
