[package]
name = "libzmq"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "libzmq"

[dependencies]
libzmq-core.workspace = true

[features]
default = ["tcp", "ipc", "inproc", "poller", "plain", "zap"]
full = [
    "curve",
    "draft",
    "gssapi",
    "ipc",
    "inproc",
    "norm",
    "openpgm",
    "plain",
    "poller",
    "tcp",
    "tipc",
    "udp",
    "vmci",
    "vsock",
    "ws",
    "wss",
    "zap",
]
curve = []
draft = []
gssapi = ["libzmq-core/gssapi"]
ipc = []
inproc = []
norm = ["libzmq-core/norm"]
openpgm = []
plain = []
poller = []
tcp = []
tipc = []
udp = []
vmci = []
vsock = []
ws = []
sodium = ["libzmq-core/sodium"]
wss = ["ws", "libzmq-core/wss"]
zap = []

[lints]
workspace = true
